<a href="https://colab.research.google.com/github/Gorantlalokesh/AI-Solution-Architect/blob/main/Numpycalibo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
array

In [ ]:
arr_1d = np.array([1, 2, 3])
print(arr_1d)

[1 2 3]


In [ ]:
values_list = [10, 20, 30, 40]
values_array = np.array([10, 20, 30, 40])
print("List:", values_list)
print("Numpy array:", values_array)
print("Array ")

In [ ]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones = np.ones((3, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
random_arr = np.random.random((2, 2))
print(random_arr)

[[0.13079081 0.83216892]
 [0.50800496 0.41167482]]


In [ ]:
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
range_arr = np.arange(0, 10, 2)
print(range_arr)

[0 2 4 6 8]


In [ ]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print("Shape:",arr.shape)
print("Size",arr.size)
print("Data type:",arr.dtype)
print("Number of dimensions:",arr.ndim)

Shape: (2, 3)
Size 6
Data type: int64
Number of dimensions: 2


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])

10


In [ ]:
arr = np.array([0, 10, 20, 30, 40, 50])

print(arr[1:4])
print(arr[:3])
print(arr[3:])
print(arr[::2])
print(arr[::-1])

matrix = np.arange(1, 13).reshape(3, 4)

print("\nMatrix:\n",matrix)
print("\nFirst two rows:\n",matrix[:2])
print("\nFirst two columns:\n",matrix[:, :2])

[10 20 30]
[ 0 10 20]
[30 40 50]
[ 0 20 40]
[50 40 30 20 10  0]

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First two rows:
 [[1 2 3 4]
 [5 6 7 8]]

First two columns:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]


In [ ]:
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
cube = arr.reshape(2, 2, 3)

print("Original:", arr)
print("\n3 * 4:",matrix)
print("\n3D shape:",cube.shape)
print(cube)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]

3 * 4: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

3D shape: (2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:",a + b)
print("Subtraction:",a - b)


Addition: [11 22 33]
Subtraction: [ 9 18 27]


In [ ]:
matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("Original:\n", matrix)
print("\nTranspose:\n", matrix.T)
print("Transpose shape:",matrix.T.shape)

print("\nFlatten:",matrix.flatten())

Original:
 [[1 2 3]
 [4 5 6]]

Transpose:
 [[1 4]
 [2 5]
 [3 6]]
Transpose shape: (3, 2)

Flatten: [1 2 3 4 5 6]


In [ ]:
arr = np.array([1, 4, 9, 16])

print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(np.array([0, 1, 2])))
print("Log:", np.log(arr))
print("Absolute value:", np.abs(arr))

Square root: [1. 2. 3. 4.]
Exponential: [1.         2.71828183 7.3890561 ]
Log: [0.         1.38629436 2.19722458 2.77258872]
Absolute value: [ 1  4  9 16]


In [4]:
import numpy as np

scores = np.array([70, 80, 90, 60, 100])

print("Sum:", np.sum(scores))
print("Mean:",np.mean(scores))
print("Median",np.median(scores))
print("Minimum",np.min(scores))
print("Maximum",np.max(scores))
print("Standard deviation",np.std(scores))

Sum: 400
Mean: 80.0
Median 80.0
Minimum 60
Maximum 100
Standard deviation 14.142135623730951


In [5]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
vector = np.array([10, 20, 30])
print(matrix + vector)

[[11 22 33]
 [14 25 36]]


In [6]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Column sums (axis=0):",np.sum(matrix, axis=0))
print("Row sums (axis=1):",np.sum(matrix, axis=1))

Column sums (axis=0): [5 7 9]
Row sums (axis=1): [ 6 15]


In [10]:
scores = np.array([35, 55, 72, 40, 90])
result = np.where(scores >= 50,"Pass","Fail")
print(result)

['Fail' 'Pass' 'Pass' 'Fail' 'Pass']


In [11]:
import numpy as np

X = np.array([[1, 2],
              [3, 4]])

Y = np.array([[5, 6],
              [7, 8]])

print("\nVertical stack:\n", np.vstack([X, Y]))

print("\nHorizontal stack:\n", np.hstack([X, Y]))


Vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [15]:
import numpy as np

rng = np.random.default_rng(42)

print("Random integers:", rng.integers(1, 10, size=8))
print("Random floats:", rng.random(5))
print("Normal distribution:", rng.normal(size=5))

Random integers: [1 7 6 4 4 8 1 7]
Random floats: [0.09417735 0.97562235 0.7611397  0.78606431 0.12811363]
Normal distribution: [-0.85304393  0.87939797  0.77779194  0.0660307   1.12724121]


In [16]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Element-wise multiplication:\n", A * B)

print("\nMatrix multiplication:\n", A @ B)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\nDot product:", np.dot(a, b))

Element-wise multiplication:
 [[ 5 12]
 [21 32]]

Matrix multiplication:
 [[19 22]
 [43 50]]

Dot product: 32


In [17]:
import numpy as np

data = np.array([10, 20, np.nan, 40, 50])

print("Is NaN:", np.isnan(data))
print("Normal mean:", np.mean(data))
print("NaN-safe mean:", np.nanmean(data))
print("NaN-safe sum:", np.nansum(data))

Is NaN: [False False  True False False]
Normal mean: nan
NaN-safe mean: 30.0
NaN-safe sum: 120.0
